export const palette = {
  background: '#f8f9ff',
  surface: '#ffffff',
  low: '#eff4ff',
  container: '#e5eeff',
  high: '#d3e4fe',
  text: '#0b1c30',
  muted: '#3c4a42',
  outline: '#bbcabf',
  primary: '#006c49',
  primaryContainer: '#10b981',
  primaryFixed: '#6ffbbe',
  secondary: '#4648d4',
  secondaryFixed: '#e1e0ff',
  tertiary: '#e29100',
  tertiaryFixed: '#ffddb8',
  danger: '#ba1a1a',
  dangerFixed: '#ffdad6',
};
