import {StyleSheet} from 'react-native';
import {palette} from '../theme/palette';

export const styles = StyleSheet.create({
  app: {backgroundColor: palette.background, flex: 1},
  shell: {alignItems: 'center', backgroundColor: palette.background, flex: 1},
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
    width: '100%',
  },
  headerTitle: {color: palette.primary, fontSize: 24, fontWeight: '800'},
  iconSpacer: {height: 40, width: 40},
  content: {gap: 16, padding: 16, paddingBottom: 112, width: '100%'},
  splash: {alignItems: 'center', flex: 1, gap: 16, justifyContent: 'center', padding: 24},
  display: {color: palette.text, fontSize: 34, fontWeight: '800', letterSpacing: 0, textAlign: 'center'},
  title: {color: palette.text, fontSize: 24, fontWeight: '800'},
  body: {color: palette.muted, fontSize: 15, lineHeight: 22},
  mutedCenter: {color: palette.muted, fontSize: 14, fontWeight: '600', textAlign: 'center'},
  brand: {
    alignItems: 'center',
    backgroundColor: palette.surface,
    borderColor: palette.high,
    borderWidth: 1,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 18,
  },
  brandCard: {
    backgroundColor: '#d9ffed',
    borderColor: palette.primary,
    borderRadius: 8,
    borderWidth: 3,
  },
  brandCoin: {backgroundColor: palette.secondary, borderRadius: 999, position: 'absolute'},
  loadingTrack: {backgroundColor: palette.container, borderRadius: 999, height: 8, marginTop: 12, overflow: 'hidden', width: 180},
  loadingFill: {backgroundColor: palette.primaryContainer, height: 8, width: 126},
  topBar: {alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between'},
  link: {color: palette.primary, fontSize: 14, fontWeight: '900'},
  heroArt: {alignItems: 'center', alignSelf: 'center', backgroundColor: palette.low, borderRadius: 220, height: 300, justifyContent: 'center', width: 300},
  phoneMock: {alignItems: 'flex-end', backgroundColor: palette.surface, borderRadius: 28, flexDirection: 'row', gap: 12, height: 210, justifyContent: 'center', padding: 22, width: 150},
  chartLine: {backgroundColor: palette.high, borderRadius: 999, height: 150, position: 'absolute', top: 24, width: 6},
  chartBar: {backgroundColor: palette.secondary, borderRadius: 999, width: 18},
  heroBarMedium: {height: 84},
  heroBarTall: {backgroundColor: palette.primaryContainer, height: 132},
  heroBarSmall: {backgroundColor: palette.tertiary, height: 58},
  dots: {flexDirection: 'row', gap: 8, justifyContent: 'center'},
  dot: {backgroundColor: palette.high, borderRadius: 999, height: 9, width: 9},
  dotActive: {backgroundColor: palette.primary, width: 30},
  card: {backgroundColor: palette.surface, borderColor: palette.high, borderRadius: 12, borderWidth: 1, gap: 14, padding: 16, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 18},
  accentCard: {backgroundColor: palette.low},
  sectionTitle: {color: palette.text, fontSize: 17, fontWeight: '800'},
  rowWrap: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  avatar: {alignItems: 'center', backgroundColor: palette.container, borderRadius: 18, height: 62, justifyContent: 'center', width: 62},
  avatarActive: {backgroundColor: palette.primary},
  avatarText: {color: '#fff', fontSize: 18, fontWeight: '900'},
  fieldWrap: {gap: 8},
  fieldLabel: {color: palette.muted, fontSize: 13, fontWeight: '800'},
  field: {backgroundColor: palette.surface, borderColor: palette.high, borderRadius: 12, borderWidth: 1, color: palette.text, fontSize: 16, paddingHorizontal: 16, paddingVertical: 12},
  largeField: {fontSize: 28, fontWeight: '900'},
  compactPicker: {marginVertical: 2},
  chip: {backgroundColor: palette.low, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9},
  activeChip: {backgroundColor: palette.primary},
  chipText: {color: palette.muted, fontWeight: '800'},
  activeChipText: {color: '#fff'},
  button: {alignItems: 'center', backgroundColor: palette.primary, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 15},
  buttonText: {color: '#fff', fontSize: 15, fontWeight: '900'},
  secondaryButton: {backgroundColor: palette.low},
  secondaryButtonText: {color: palette.primary},
  dangerButton: {backgroundColor: palette.dangerFixed},
  dangerButtonText: {color: palette.danger},
  iconButton: {alignItems: 'center', backgroundColor: palette.low, borderRadius: 999, height: 40, justifyContent: 'center', width: 40},
  iconButtonText: {color: palette.primary, fontSize: 20, fontWeight: '900'},
  infoRow: {alignItems: 'center', flexDirection: 'row', gap: 12, minHeight: 56},
  rowGlyph: {alignItems: 'center', backgroundColor: '#d9ffed', borderRadius: 10, height: 38, justifyContent: 'center', width: 38},
  rowGlyphText: {color: palette.primary, fontWeight: '900'},
  rowBody: {flex: 1},
  rowTitle: {color: palette.text, fontSize: 15, fontWeight: '800'},
  rowSubtitle: {color: palette.muted, fontSize: 12, marginTop: 2},
  rowValue: {color: palette.text, fontSize: 15, fontWeight: '900'},
  negative: {color: palette.danger},
  chevron: {color: palette.outline, fontSize: 28},
  successBadge: {alignItems: 'center', alignSelf: 'center', backgroundColor: '#d9ffed', borderRadius: 999, height: 116, justifyContent: 'center', width: 116},
  successText: {color: palette.primary, fontSize: 32, fontWeight: '900'},
  authIntro: {alignItems: 'center', gap: 14},
  pinRow: {flexDirection: 'row', gap: 10, justifyContent: 'center'},
  pinBox: {alignItems: 'center', backgroundColor: palette.surface, borderColor: palette.high, borderRadius: 12, borderWidth: 1, height: 56, justifyContent: 'center', width: 56},
  pinText: {color: palette.text, fontSize: 28, fontWeight: '900'},
  keypad: {flexDirection: 'row', flexWrap: 'wrap', gap: 14, justifyContent: 'center'},
  key: {alignItems: 'center', backgroundColor: palette.surface, borderRadius: 14, height: 58, justifyContent: 'center', width: '28%'},
  keyText: {color: palette.text, fontSize: 18, fontWeight: '800'},
  cardLabel: {color: palette.muted, fontSize: 13, fontWeight: '800'},
  balance: {color: palette.text, fontSize: 34, fontWeight: '900', letterSpacing: 0},
  metricGrid: {flexDirection: 'row', gap: 8},
  metric: {backgroundColor: palette.surface, borderRadius: 10, flex: 1, padding: 10},
  metricLabel: {color: palette.muted, fontSize: 11, fontWeight: '800'},
  metricValue: {color: palette.text, fontSize: 14, fontWeight: '900', marginTop: 4},
  cardHeader: {alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between'},
  progressTrack: {backgroundColor: palette.container, borderRadius: 999, height: 10, overflow: 'hidden'},
  progressFill: {backgroundColor: palette.primaryContainer, borderRadius: 999, height: 10},
  chart: {alignItems: 'flex-end', flexDirection: 'row', gap: 10, height: 130, justifyContent: 'space-between'},
  chartBarNative: {backgroundColor: palette.secondary, borderRadius: 999, flex: 1, maxWidth: 48},
  donut: {alignItems: 'center', alignSelf: 'center', backgroundColor: palette.primaryContainer, borderColor: palette.secondary, borderRadius: 999, borderWidth: 34, height: 170, justifyContent: 'center', width: 170},
  donutHole: {backgroundColor: palette.surface, borderRadius: 999, height: 72, width: 72},
  segment: {backgroundColor: palette.container, borderRadius: 12, flexDirection: 'row', gap: 8, padding: 8},
  search: {backgroundColor: palette.surface, borderColor: palette.high, borderRadius: 999, borderWidth: 1, color: palette.muted, fontSize: 15, paddingHorizontal: 18, paddingVertical: 12},
  detailAmount: {color: palette.danger, fontSize: 42, fontWeight: '900'},
  receipt: {alignItems: 'center', backgroundColor: palette.low, borderRadius: 12, height: 130, justifyContent: 'center'},
  actionGrid: {flexDirection: 'row', gap: 10},
  profileTop: {alignItems: 'center', flexDirection: 'row', gap: 14},
  switchTrack: {backgroundColor: palette.high, borderRadius: 999, height: 28, justifyContent: 'center', padding: 3, width: 52},
  switchOn: {backgroundColor: palette.primaryContainer},
  switchThumb: {backgroundColor: palette.surface, borderRadius: 999, height: 22, width: 22},
  switchThumbOn: {transform: [{translateX: 24}]},
  swatch: {borderRadius: 999, height: 38, width: 38},
  tabBar: {alignSelf: 'center', backgroundColor: palette.surface, borderColor: palette.high, borderRadius: 18, borderWidth: 1, bottom: 16, flexDirection: 'row', gap: 4, left: 16, maxWidth: 620, padding: 8, position: 'absolute', right: 16},
  tabItem: {alignItems: 'center', borderRadius: 12, flex: 1, paddingVertical: 11},
  activeTab: {backgroundColor: '#d9ffed'},
  addTab: {backgroundColor: palette.primary},
  tabText: {color: palette.muted, fontSize: 11, fontWeight: '800'},
  activeTabText: {color: palette.primary},
  addTabText: {color: '#fff'},
});
